#!/bin/sh
# This script takes no argument and uses SERVICE_PORT and PORT0 environment variables
# to setup /etc/envoy/envoy.yaml file.
# SERVICE_PORT and PORT0 must be set

# check if SERVICE_PORT is present
if [ "$SERVICE_PORT" ]; then
  echo "$(date -Is) SERVICE_PORT is set"
else
  echo "$(date -Is) SERVICE_PORT is not set. Exiting envoy-start"
  exit 1
fi

# check if PORT0 is present
if [ "$PORT0" ]; then
  echo "$(date -Is) PORT0 is set"
else
  echo "$(date -Is) PORT0 is not set. Exiting envoy-start"
  exit 1
fi

if [ ${HEALTH_CHECK_PORT_INDEX:-0} -gt 0 ]; then
    echo "$(date -Is) HEALTH_CHECK_PORT_INDEX is positive"
    PROXY_PORT_COUNT=2
else
    PROXY_PORT_COUNT=1
fi

CONFIG_YAML=/etc/envoy/envoy${PROXY_PORT_COUNT}.yaml

echo "$(date -Is) Substituting variables in configuration template"

# change the SERVICE_PORT and PORT0 values in /etc/envoy/envoy.yaml to respective env variables
(
set -x
sed -i \
    -e "s/{{APP_PORT}}/${PORT0}/g" \
    -e "s/{{HC_PORT}}/$(( PORT0 + HEALTH_CHECK_PORT_INDEX ))/g" \
    -e "s/{{PROXY_APP_PORT}}/${SERVICE_PORT}/g" \
    -e "s/{{PROXY_HC_PORT}}/$(( SERVICE_PORT + HEALTH_CHECK_PORT_INDEX ))/g" \
    ${CONFIG_YAML}
)

echo "$(date -Is) Starting envoy"

# start envoy with /etc/envoy/envoy.yaml config file
exec envoy -c ${CONFIG_YAML} --base-id 1
