#!/bin/sh

# Set default server port
: ${WAITER_FILESERVER_PORT:=9090}
export WAITER_FILESERVER_PORT

# Generate server config from template
envsubst </root/nginx.conf.template >/root/nginx.conf

# Start server in non-daemon mode, replacing current process
exec nginx -c /root/nginx.conf
