name: 'Waiter token-syncer tests'

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - 'build**'
  schedule:
    - cron: '0 0 * * *'

jobs:
  test:
    runs-on: ubuntu-16.04

    steps:
      - uses: actions/checkout@v2
      - name: Setup apt dependencies
        run: sudo apt-get install nginx
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/project.clj') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Run token-syncer tests
        run: cd token-syncer && ./bin/ci/run-all-tests.sh
        env:
          GDRIVE_LOG_POST_URL: https://script.google.com/macros/s/AKfycbzYm-MeTnXcIqjOFkJ2godiOsHgwjeTJcn8JbAC/exec
